tags:
  - name: Hello Swagger
get:
  description: Menyapa Hello World
responses:
  '200':
    description: Successful response
  '400':
    description: Bad Request
  '500':
    description: Internal Server Error
